# Generated by Django 4.2.13 on 2024-05-24 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleId', models.DecimalField(decimal_places=2, max_digits=10, unique=True)),
                ('cell0_soc', models.DecimalField(decimal_places=2, help_text='State of Charge for Cell 0', max_digits=5)),
                ('cell0_voltage', models.DecimalField(decimal_places=2, help_text='Voltage for Cell 0', max_digits=5)),
                ('cell1_soc', models.DecimalField(decimal_places=2, help_text='State of Charge for Cell 1', max_digits=5)),
                ('cell1_voltage', models.DecimalField(decimal_places=2, help_text='Voltage for Cell 1', max_digits=5)),
                ('cell2_soc', models.DecimalField(decimal_places=2, help_text='State of Charge for Cell 2', max_digits=5)),
                ('cell2_voltage', models.DecimalField(decimal_places=2, help_text='Voltage for Cell 2', max_digits=5)),
                ('cell3_soc', models.DecimalField(decimal_places=2, help_text='State of Charge for Cell 3', max_digits=5)),
                ('cell3_voltage', models.DecimalField(decimal_places=2, help_text='Voltage for Cell 3', max_digits=5)),
            ],
        ),
    ]
