# Generated by Django 4.2.13 on 2024-05-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BMSmonitor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='moduleId',
        ),
        migrations.AddField(
            model_name='module',
            name='charge_flag',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Charge Flag', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='tempertaure',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Charge Flag', max_digits=5),
            preserve_default=False,
        ),
    ]
