# Generated by Django 4.2.13 on 2024-05-28 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BMSmonitor', '0002_remove_module_moduleid_module_charge_flag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='tempertaure',
            new_name='temperature',
        ),
    ]
